DROP DATABASE IF EXISTS fabrica_pelotas;

CREATE DATABASE fabrica_pelotas;

SELECT pg_terminate_backend(pg_stat_activity.pid)
FROM pg_stat_activity
WHERE pg_stat_activity.datname = 'fabrica_pelotas' AND pid <> pg_backend_pid();

\connect postgres  -- Reconectarse temporalmente a 'postgres' para evitar bloqueos
\connect fabrica_pelotas  -- Cambiar a la nueva DB

CREATE TABLE "dificultad" (
	"id_dificultad" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"nombre_dificultad" INTEGER NOT NULL,
	PRIMARY KEY("id_dificultad")
);

CREATE TABLE "marca" (
	"id_marca" INTEGER NOT NULL,
	"nombre_marca" VARCHAR(45) NOT NULL,
	PRIMARY KEY("id_marca")
);

CREATE TABLE "proceso_planta" (
	"id_proceso_planta" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"planta_color" VARCHAR(45) NOT NULL,
	"proceso_id" INTEGER NOT NULL,
	PRIMARY KEY("id_proceso_planta")
);

CREATE TABLE "procesos" (
	"id_procesos" INTEGER NOT NULL UNIQUE,
	"nombre_proceso" VARCHAR(45) NOT NULL,
	"id_dificultad" INTEGER NOT NULL,
	PRIMARY KEY("id_procesos")
);

CREATE TABLE "plantas" (
	"color_planta" VARCHAR(45) NOT NULL UNIQUE,
	"nombre_planta" VARCHAR(45) NOT NULL,
	"superficie" DECIMAL(5,2) NOT NULL,
	PRIMARY KEY("color_planta")
);

CREATE TABLE "tecnico" (
	"dni" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"nombre_tecnico" VARCHAR(45) NOT NULL,
	"apellido_tecnico_1" VARCHAR(45) NOT NULL,
	"apellido_tecnico_2" VARCHAR(45) NOT NULL,
	"fecha_nacimiento" INTEGER NOT NULL,
	"telefono_1" VARCHAR(10) NOT NULL,
	"telefono_2" VARCHAR(10),
	"telefono_3" VARCHAR(10),
	PRIMARY KEY("dni")
);

CREATE TABLE "asignaciones" (
	"id_asignacion" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"maquina_id_1" INTEGER NOT NULL,
	"maquina_id_2" INTEGER NOT NULL,
	"tecnico_dni" INTEGER NOT NULL,
	"turno_id" INTEGER NOT NULL,
	"fecha_inicio" INTEGER NOT NULL,
	"fecha_fin" INTEGER NOT NULL,
	PRIMARY KEY("id_asignacion")
);

CREATE TABLE "maquina" (
	"id_maquina" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"marca_id" INTEGER NOT NULL,
	"modelo_maquina" VARCHAR(45) NOT NULL,
	"no_serie" VARCHAR(45) NOT NULL,
	"proceso_planta_id" INTEGER NOT NULL,
	"estatus" SMALLINT NOT NULL,
	PRIMARY KEY("id_maquina")
);

CREATE TABLE "turno" (
	"id_turno" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"nombre_turno" VARCHAR(15) NOT NULL,
	"hora_inicio" INTEGER NOT NULL,
	"hora_fin" INTEGER NOT NULL,
	PRIMARY KEY("id_turno")
);

ALTER TABLE "plantas"
ADD FOREIGN KEY("color_planta") REFERENCES "proceso_planta"("planta_color")
ON UPDATE NO ACTION ON DELETE SET NULL;

ALTER TABLE "procesos"
ADD FOREIGN KEY("id_procesos") REFERENCES "proceso_planta"("proceso_id")
ON UPDATE NO ACTION ON DELETE SET NULL;

ALTER TABLE "dificultad"
ADD FOREIGN KEY("id_dificultad") REFERENCES "procesos"("id_dificultad")
ON UPDATE NO ACTION ON DELETE SET NULL;

ALTER TABLE "marca"
ADD FOREIGN KEY("id_marca") REFERENCES "maquina"("marca_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "maquina"
ADD FOREIGN KEY("id_maquina") REFERENCES "asignaciones"("maquina_id_1")
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "maquina"
ADD FOREIGN KEY("id_maquina") REFERENCES "asignaciones"("maquina_id_2")
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "tecnico"
ADD FOREIGN KEY("dni") REFERENCES "asignaciones"("tecnico_dni")
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "turno"
ADD FOREIGN KEY("id_turno") REFERENCES "asignaciones"("turno_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;