-- Eliminar la base de datos si existe
DROP DATABASE IF EXISTS fabrica_pelotas;

-- Crear la base de datos nuevamente
CREATE DATABASE fabrica_pelotas;

-- Conectarse a la base de datos (esto normalmente se haría fuera del script)
-- \c tu_base_de_datos

-- Crear las tablas
CREATE TABLE "Plantas" (
	"colorPlanta" VARCHAR(45) NOT NULL UNIQUE,
	"nombrePlanta" VARCHAR(45),
	"superficie" DECIMAL(5,2),
	PRIMARY KEY("colorPlanta")
);

CREATE TABLE "Procesos" (
	"idProcesos" INTEGER NOT NULL UNIQUE,
	"nombreProceso" VARCHAR(45),
	"idDificultad" INTEGER,
	PRIMARY KEY("idProcesos")
);

CREATE TABLE "Dificultad" (
	"idDificultad" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"nombreDificultad" VARCHAR(45),
	PRIMARY KEY("idDificultad")
);
CREATE INDEX "Dificultad_index_0"
ON "Dificultad" ();

CREATE TABLE "ProcesoPlanta" (
	"idProcesoPlanta" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"plantaColor" VARCHAR(45),
	"procesoId" INTEGER,
	PRIMARY KEY("idProcesoPlanta")
);

CREATE TABLE "Marca" (
	"idMarca" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"nombreMarca" VARCHAR(45),
	PRIMARY KEY("idMarca")
);

CREATE TABLE "Maquina" (
	"idMaquina" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"idMarca" INTEGER,
	"modeloMaquina" VARCHAR(45),
	"noSerie" VARCHAR(45),
	"idProcesoPlanta" INTEGER,
	"estatus" INTEGER,
	PRIMARY KEY("idMaquina")
);

CREATE TABLE "Tecnico" (
	"dni" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"nombre" VARCHAR(45),
	"apellido" VARCHAR(45),
	"fechaNacimiento" INTEGER,
	"telefono1" VARCHAR(10),
	"telefono2" VARCHAR(10) NOT NULL,
	"telefono3" VARCHAR(10) NOT NULL,
	PRIMARY KEY("dni")
);

CREATE TABLE "Turno" (
	"idTurno" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"nombreTurno" VARCHAR(15),
	"horaInicio" INTEGER,
	"horaFin" INTEGER,
	PRIMARY KEY("idTurno")
);

CREATE TABLE "Asignacion" (
	"idAsignacion" INTEGER NOT NULL UNIQUE,
	"maquinaId1" INTEGER,
	"maquinaId2" INTEGER NOT NULL,
	"tecnicoDni" INTEGER,
	"idTurno" INTEGER,
	"fechaInicio" INTEGER,
	"fechaFin" INTEGER,
	PRIMARY KEY("idAsignacion")
);

ALTER TABLE "ProcesoPlanta"
ADD FOREIGN KEY("procesoId") REFERENCES "Procesos"("idProcesos")
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "ProcesoPlanta"
ADD FOREIGN KEY("plantaColor") REFERENCES "Plantas"("colorPlanta")
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "Marca"
ADD FOREIGN KEY("idMarca") REFERENCES "Maquina"("idMarca")
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "Maquina"
ADD FOREIGN KEY("idProcesoPlanta") REFERENCES "ProcesoPlanta"("idProcesoPlanta")
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "Tecnico"
ADD FOREIGN KEY("dni") REFERENCES "Asignacion"("tecnicoDni")
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "Turno"
ADD FOREIGN KEY("idTurno") REFERENCES "Asignacion"("idTurno")
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "Maquina"
ADD FOREIGN KEY("idMaquina") REFERENCES "Asignacion"("maquinaId1")
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "Maquina"
ADD FOREIGN KEY("idMaquina") REFERENCES "Asignacion"("maquinaId2")
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "Procesos"
ADD FOREIGN KEY("idDificultad") REFERENCES "Dificultad"("idDificultad")
ON UPDATE NO ACTION ON DELETE NO ACTION;